### ISSUE TITLE
Widescreen doesn't 're-enable' when going to main menu and joining a new game

### ISSUE THREAD

**Issue by h-exx** [stefan750/LCUltrawide#3]
Starting my first game:
![image](https://github.com/stefan750/LCUltrawide/assets/17961641/29d429dd-05c6-4e94-8b73-4a1f8652f598)

Press quit and then load any new/loaded game
![image](https://github.com/stefan750/LCUltrawide/assets/17961641/f5fb22ef-004e-4411-a570-09e9ddc27572)

**Comment by stefan750** [comment]
Thank you for the report!
This along with some other issues is fixed in version 1.1.1.
